name: Deploy to production environment

on:
  push:
    tags:
      - 'v*.*'

jobs:
  deploy:
    name: Deploy landing page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download minio
        run: |
          curl https://dl.minio.io/client/mc/release/linux-amd64/mc --output ./mc
          chmod u+x ./mc
      - name: Setup alias
        run: ./mc alias set upload https://s3.eu-de.cloud-object-storage.appdomain.cloud ${{ secrets.IBM_COS_ACCESS_KEY }} ${{ secrets.IBM_COS_SECRET_KEY }}
      - name: Upload files
        run: |
          ./mc cp -r css upload/website-bavi/
          ./mc cp -r icons upload/website-bavi/
          ./mc cp -r js upload/website-bavi/
          ./mc cp qgis/Readme.txt upload/website-bavi/qgis/Readme.txt
          ./mc cp -r video upload/website-bavi/
          ./mc cp -r svg upload/website-bavi/
          ./mc cp -r status upload/website-bavi/
          ./mc cp index.html upload/website-bavi/
          ./mc cp robots.txt upload/website-bavi/
          ./mc cp sitemap.xml upload/website-bavi/
